//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC4_Validacion_Data_Annotation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int codigo_c { get; set; }
        public string nombre_c { get; set; }
        public string correo_c { get; set; }
        public int credito_c { get; set; }
    }
}
