//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC4_Validacion_Data_Annotation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string usuario_u { get; set; }
        public string clave_u { get; set; }
        public string nombreUsuario_u { get; set; }
    }
}
